name: CI

on: 
  push:
    branches: master
    tags: v*
  pull_request:
    branches: master

jobs:
  ci:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Rust toolchains
      if: runner.OS != 'Linux'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Caching
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name: Build
      run: cargo build --verbose
    - name: Code Format
      run: cargo fmt --all -- --check
    - name: Clippy Check
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
